# Generated by Django 5.0.4 on 2024-05-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='agrees',
            new_name='agree',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='disagrees',
            new_name='disagree',
        ),
        migrations.AddField(
            model_name='poll',
            name='agreeRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='disagreeRate',
            field=models.FloatField(default=0),
        ),
    ]
